const calellaPhotoArr = [
    { id: 1, src: '/photo/calella/calella1.jpg', alt: 'Calella' },
    { id: 2, src: '/photo/calella/calella2.jpg', alt: 'Calella' },
    { id: 3, src: '/photo/calella/calella3.jpg', alt: 'Calella' },
    { id: 4, src: '/photo/calella/calella4.jpg', alt: 'Calella' },
    { id: 5, src: '/photo/calella/calella5.jpg', alt: 'Calella' },
    { id: 6, src: '/photo/calella/calella6.jpg', alt: 'Calella' },
    { id: 7, src: '/photo/calella/calella7.jpg', alt: 'Calella' },
    { id: 8, src: '/photo/calella/calella8.jpg', alt: 'Calella' },
    { id: 9, src: '/photo/calella/calella9.jpg', alt: 'Calella' },
    { id: 10, src: '/photo/calella/calella10.jpg', alt: 'Calella' },
    { id: 11, src: '/photo/calella/calella11.jpg', alt: 'Calella' },
    { id: 12, src: '/photo/calella/calella12.jpg', alt: 'Calella' },
    { id: 13, src: '/photo/calella/calella13.jpg', alt: 'Calella' },
    { id: 14, src: '/photo/calella/calella14.jpg', alt: 'Calella' },
    { id: 15, src: '/photo/calella/calella15.jpg', alt: 'Calella' },
    { id: 16, src: '/photo/calella/calella16.jpg', alt: 'Calella' },
    { id: 17, src: '/photo/calella/calella17.jpg', alt: 'Calella' },
    { id: 18, src: '/photo/calella/calella18.jpg', alt: 'Calella' },
    { id: 19, src: '/photo/calella/calella19.jpg', alt: 'Calella' },
    { id: 20, src: '/photo/calella/calella20.jpg', alt: 'Calella' },
    { id: 21, src: '/photo/calella/calella21.jpg', alt: 'Calella' },
    { id: 22, src: '/photo/calella/calella22.jpg', alt: 'Calella' },
    { id: 23, src: '/photo/calella/calella23.jpg', alt: 'Calella' },
    { id: 24, src: '/photo/calella/calella24.jpg', alt: 'Calella' },
    { id: 25, src: '/photo/calella/calella25.jpg', alt: 'Calella' },
    { id: 26, src: '/photo/calella/calella26.jpg', alt: 'Calella' },
    { id: 27, src: '/photo/calella/calella27.jpg', alt: 'Calella' },
    { id: 28, src: '/photo/calella/calella28.jpg', alt: 'Calella' },
    { id: 29, src: '/photo/calella/calella29.jpg', alt: 'Calella' },
    { id: 30, src: '/photo/calella/calella30.jpg', alt: 'Calella' },
    { id: 31, src: '/photo/calella/calella31.jpg', alt: 'Calella' },
    { id: 32, src: '/photo/calella/calella32.jpg', alt: 'Calella' },
    { id: 33, src: '/photo/calella/calella33.jpg', alt: 'Calella' },
    { id: 34, src: '/photo/calella/calella34.jpg', alt: 'Calella' },
    { id: 35, src: '/photo/calella/calella35.jpg', alt: 'Calella' },
    { id: 36, src: '/photo/calella/calella36.jpg', alt: 'Calella' },
    { id: 37, src: '/photo/calella/calella37.jpg', alt: 'Calella' },
    { id: 38, src: '/photo/calella/calella38.jpg', alt: 'Calella' },
    { id: 39, src: '/photo/calella/calella39.jpg', alt: 'Calella' },
    { id: 40, src: '/photo/calella/calella40.jpg', alt: 'Calella' },
    { id: 41, src: '/photo/calella/calella41.jpg', alt: 'Calella' },
    { id: 42, src: '/photo/calella/calella42.jpg', alt: 'Calella' },    

];

export default calellaPhotoArr;