const peruPhotoArr = [    
    {id:'arequipaColca1',      src:'/photo/peru/arequipaColca1.jpg',      alt:'Arequipa y Colca'},
    {id:'arequipaColca2',      src:'/photo/peru/arequipaColca2.jpg',      alt:'Arequipa y Colca'},
    {id:'arequipaColca3',      src:'/photo/peru/arequipaColca3.jpg',      alt:'Arequipa y Colca'},
    {id:'arequipaColca4',      src:'/photo/peru/arequipaColca4.jpg',      alt:'Arequipa y Colca'},
    {id:'arequipaColca5',      src:'/photo/peru/arequipaColca5.jpg',      alt:'Arequipa y Colca'},
    {id:'arequipaColca6',      src:'/photo/peru/arequipaColca6.jpg',      alt:'Arequipa y Colca'},
    {id:'arequipaColca7',      src:'/photo/peru/arequipaColca7.jpg',      alt:'Arequipa y Colca'},
    {id:'arequipaColca8',      src:'/photo/peru/arequipaColca8.jpg',      alt:'Arequipa y Colca'},
    {id:'arequipaColca9',      src:'/photo/peru/arequipaColca9.jpg',      alt:'Arequipa y Colca'},
    {id:'arequipaColca10',     src:'/photo/peru/arequipaColca10.jpg',     alt:'Arequipa y Colca'},
    {id:'arequipaColca11',     src:'/photo/peru/arequipaColca11.jpg',     alt:'Arequipa y Colca'},
    {id:'arequipaColca12',     src:'/photo/peru/arequipaColca12.jpg',     alt:'Arequipa y Colca'},
    {id:'arequipaColca13',     src:'/photo/peru/arequipaColca13.jpg',     alt:'Arequipa y Colca'},
    {id:'arequipaColca14',     src:'/photo/peru/arequipaColca14.jpg',     alt:'Arequipa y Colca'},
    {id:'arequipaColca15',     src:'/photo/peru/arequipaColca15.jpg',     alt:'Arequipa y Colca'},
    {id:'arequipaColca16',     src:'/photo/peru/arequipaColca16.jpg',     alt:'Arequipa y Colca'},
    {id:'arequipaColca17',     src:'/photo/peru/arequipaColca17.jpg',     alt:'Arequipa y Colca'},
    {id:'arequipaColca18',     src:'/photo/peru/arequipaColca18.jpg',     alt:'Arequipa y Colca'},
    {id:'arequipaColca19',     src:'/photo/peru/arequipaColca19.jpg',     alt:'Arequipa y Colca'},
    {id:'arequipaColca20',     src:'/photo/peru/arequipaColca20.jpg',     alt:'Arequipa y Colca'},
    {id:'arequipaColca21',     src:'/photo/peru/arequipaColca21.jpg',     alt:'Arequipa y Colca'},
    {id:'arequipaColca22',     src:'/photo/peru/arequipaColca22.jpg',     alt:'Arequipa y Colca'},
    {id:'arequipaColca23',     src:'/photo/peru/arequipaColca23.jpg',     alt:'Arequipa y Colca'},
    {id:'arequipaColca24',     src:'/photo/peru/arequipaColca24.jpg',     alt:'Arequipa y Colca'},
    {id:'arequipaColca25',     src:'/photo/peru/arequipaColca25.jpg',     alt:'Arequipa y Colca'},
    {id:'arequipaColca26',     src:'/photo/peru/arequipaColca26.jpg',     alt:'Arequipa y Colca'},
    {id:'arequipaColca27',     src:'/photo/peru/arequipaColca27.jpg',     alt:'Arequipa y Colca'},
    {id:'arequipaColca28',     src:'/photo/peru/arequipaColca28.jpg',     alt:'Arequipa y Colca'},
    {id:'colca1',              src:'/photo/peru/colca1.jpg',              alt:'Colca'},
    {id:'colca2',              src:'/photo/peru/colca2.jpg',              alt:'Colca'},
    {id:'colca3',              src:'/photo/peru/colca3.jpg',              alt:'Colca'},
    {id:'colca4',              src:'/photo/peru/colca4.jpg',              alt:'Colca'},
    {id:'colca5',              src:'/photo/peru/colca5.jpg',              alt:'Colca'},
    {id:'colca6',              src:'/photo/peru/colca6.jpg',              alt:'Colca'},
    {id:'colca7',              src:'/photo/peru/colca7.jpg',              alt:'Colca'},
    {id:'colca8',              src:'/photo/peru/colca8.jpg',              alt:'Colca'},
    {id:'colca9',              src:'/photo/peru/colca9.jpg',              alt:'Colca'},
    {id:'colca10',             src:'/photo/peru/colca10.jpg',             alt:'Colca'},
    {id:'colca11',             src:'/photo/peru/colca11.jpg',             alt:'Colca'},
    {id:'colca12',             src:'/photo/peru/colca12.jpg',             alt:'Colca'},
    {id:'colca13',             src:'/photo/peru/colca13.jpg',             alt:'Colca'},
    {id:'colca14',             src:'/photo/peru/colca14.jpg',             alt:'Colca'},
    {id:'colca15',             src:'/photo/peru/colca15.jpg',             alt:'Colca'},
    {id:'colca16',             src:'/photo/peru/colca16.jpg',             alt:'Colca'},
    {id:'colca17',             src:'/photo/peru/colca17.jpg',             alt:'Colca'},
    {id:'colca18',             src:'/photo/peru/colca18.jpg',             alt:'Colca'},
    {id:'colca19',             src:'/photo/peru/colca19.jpg',             alt:'Colca'},
    {id:'colca20',             src:'/photo/peru/colca20.jpg',             alt:'Colca'},
    {id:'colca21',             src:'/photo/peru/colca21.jpg',             alt:'Colca'},
    {id:'colca22',             src:'/photo/peru/colca22.jpg',             alt:'Colca'},
    {id:'colca23',             src:'/photo/peru/colca23.jpg',             alt:'Colca'},
    {id:'colca24',             src:'/photo/peru/colca24.jpg',             alt:'Colca'},
    {id:'colca25',             src:'/photo/peru/colca25.jpg',             alt:'Colca'},
    {id:'colca26',             src:'/photo/peru/colca26.jpg',             alt:'Colca'},
    {id:'colca27',             src:'/photo/peru/colca27.jpg',             alt:'Colca'},
    {id:'titicaca1',           src:'/photo/peru/titicaca1.jpg',           alt:'Lago Titicaca'},
    {id:'titicaca2',           src:'/photo/peru/titicaca2.jpg',           alt:'Lago Titicaca'},
    {id:'titicaca3',           src:'/photo/peru/titicaca3.jpg',           alt:'Lago Titicaca'},
    {id:'titicaca4',           src:'/photo/peru/titicaca4.jpg',           alt:'Lago Titicaca'},
    {id:'titicaca5',           src:'/photo/peru/titicaca5.jpg',           alt:'Lago Titicaca'},
    {id:'titicaca6',           src:'/photo/peru/titicaca6.jpg',           alt:'Lago Titicaca'},
    {id:'titicaca7',           src:'/photo/peru/titicaca7.jpg',           alt:'Lago Titicaca'},
    {id:'titicaca8',           src:'/photo/peru/titicaca8.jpg',           alt:'Lago Titicaca'},
    {id:'titicaca9',           src:'/photo/peru/titicaca9.jpg',           alt:'Lago Titicaca'},
    {id:'titicaca10',          src:'/photo/peru/titicaca10.jpg',          alt:'Lago Titicaca'},
    {id:'titicaca11',          src:'/photo/peru/titicaca11.jpg',          alt:'Lago Titicaca'},
    {id:'titicaca12',          src:'/photo/peru/titicaca12.jpg',          alt:'Lago Titicaca'},
    {id:'titicaca13',          src:'/photo/peru/titicaca13.jpg',          alt:'Lago Titicaca'},
    {id:'titicaca14',          src:'/photo/peru/titicaca14.jpg',          alt:'Lago Titicaca'},
    {id:'titicaca15',          src:'/photo/peru/titicaca15.jpg',          alt:'Lago Titicaca'},
    {id:'titicaca16',          src:'/photo/peru/titicaca16.jpg',          alt:'Lago Titicaca'},
    {id:'titicaca17',          src:'/photo/peru/titicaca17.jpg',          alt:'Lago Titicaca'},
    {id:'titicaca18',          src:'/photo/peru/titicaca18.jpg',          alt:'Lago Titicaca'},
    {id:'titicaca19',          src:'/photo/peru/titicaca19.jpg',          alt:'Lago Titicaca'},
    {id:'titicaca20',          src:'/photo/peru/titicaca20.jpg',          alt:'Lago Titicaca'},
    {id:'titicaca21',          src:'/photo/peru/titicaca21.jpg',          alt:'Lago Titicaca'},
    {id:'titicaca22',          src:'/photo/peru/titicaca22.jpg',          alt:'Lago Titicaca'},
    {id:'titicaca23',          src:'/photo/peru/titicaca23.jpg',          alt:'Lago Titicaca'},
    {id:'titicaca24',          src:'/photo/peru/titicaca24.jpg',          alt:'Lago Titicaca'},
    {id:'tren1',               src:'/photo/peru/tren1.jpg',               alt:'Tren de Arequipa a Cuzco'},
    {id:'tren2',               src:'/photo/peru/tren2.jpg',               alt:'Tren de Arequipa a Cuzco'},
    {id:'tren3',               src:'/photo/peru/tren3.jpg',               alt:'Tren de Arequipa a Cuzco'},
    {id:'tren4',               src:'/photo/peru/tren4.jpg',               alt:'Tren de Arequipa a Cuzco'},
    {id:'tren5',               src:'/photo/peru/tren5.jpg',               alt:'Tren de Arequipa a Cuzco'},
    {id:'tren6',               src:'/photo/peru/tren6.jpg',               alt:'Tren de Arequipa a Cuzco'},
    {id:'tren7',               src:'/photo/peru/tren7.jpg',               alt:'Tren de Arequipa a Cuzco'},
    {id:'tren8',               src:'/photo/peru/tren8.jpg',               alt:'Tren de Arequipa a Cuzco'},
    {id:'tren9',               src:'/photo/peru/tren9.jpg',               alt:'Tren de Arequipa a Cuzco'},
    {id:'tren10',              src:'/photo/peru/tren10.jpg',              alt:'Tren de Arequipa a Cuzco'},
    // {id:'', ph":src='/ph    oto/peru/tren11.jpg' alt="Tren de Arequ    ipa:' Cuzco"></'},
    {id:'tren12',              src:'/photo/peru/tren12.jpg',              alt:'Tren de Arequipa a Cuzco'},
    {id:'tren13',              src:'/photo/peru/tren13.jpg',              alt:'Tren de Arequipa a Cuzco'},
    {id:'tren14',              src:'/photo/peru/tren14.jpg',              alt:'Tren de Arequipa a Cuzco'},
    {id:'tren15',              src:'/photo/peru/tren15.jpg',              alt:'Tren de Arequipa a Cuzco'},
    {id:'tren16',              src:'/photo/peru/tren16.jpg',              alt:'Tren de Arequipa a Cuzco'},
    {id:'tren17',              src:'/photo/peru/tren17.jpg',              alt:'Tren de Arequipa a Cuzco'},
    {id:'tren18',              src:'/photo/peru/tren18.jpg',              alt:'Tren de Arequipa a Cuzco'},
    {id:'tren19',              src:'/photo/peru/tren19.jpg',              alt:'Tren de Arequipa a Cuzco'},
    {id:'tren20',              src:'/photo/peru/tren20.jpg',              alt:'Tren de Arequipa a Cuzco'},
    {id:'tren21',              src:'/photo/peru/tren21.jpg',              alt:'Tren de Arequipa a Cuzco'},
    {id:'tren22',              src:'/photo/peru/tren22.jpg',              alt:'Tren de Arequipa a Cuzco'},
    {id:'tren23',              src:'/photo/peru/tren23.jpg',              alt:'Tren de Arequipa a Cuzco'},
    {id:'machuPicchu1',        src:'/photo/peru/machuPicchu1.jpg',        alt:'Machu Picchu'},
    {id:'machuPicchu2',        src:'/photo/peru/machuPicchu2.jpg',        alt:'Machu Picchu'},
    {id:'machuPicchu3',        src:'/photo/peru/machuPicchu3.jpg',        alt:'Machu Picchu'},
    {id:'machuPicchu4',        src:'/photo/peru/machuPicchu4.jpg',        alt:'Machu Picchu'},
    {id:'machuPicchu5',        src:'/photo/peru/machuPicchu5.jpg',        alt:'Machu Picchu'},
    {id:'machuPicchu6',        src:'/photo/peru/machuPicchu6.jpg',        alt:'Machu Picchu'},
    {id:'machuPicchu7',        src:'/photo/peru/machuPicchu7.jpg',        alt:'Machu Picchu'},
    {id:'machuPicchu8',        src:'/photo/peru/machuPicchu8.jpg',        alt:'Machu Picchu'},
    {id:'machuPicchu9',        src:'/photo/peru/machuPicchu9.jpg',        alt:'Machu Picchu'},
    {id:'machuPicchu10',       src:'/photo/peru/machuPicchu10.jpg',       alt:'Machu Picchu'},
    {id:'machuPicchu11',       src:'/photo/peru/machuPicchu11.jpg',       alt:'Machu Picchu'},
    {id:'machuPicchu12',       src:'/photo/peru/machuPicchu12.jpg',       alt:'Machu Picchu'},
    {id:'machuPicchu13',       src:'/photo/peru/machuPicchu13.jpg',       alt:'Machu Picchu'},
    {id:'machuPicchu14',       src:'/photo/peru/machuPicchu14.jpg',       alt:'Machu Picchu'},
    {id:'machuPicchu15',       src:'/photo/peru/machuPicchu15.jpg',       alt:'Machu Picchu'},
    {id:'machuPicchu16',       src:'/photo/peru/machuPicchu16.jpg',       alt:'Machu Picchu'},
    {id:'huaynaPicchuClimb1',  src:'/photo/peru/huaynaPicchuClimb1.jpg',  alt:'Huayna Picchu'},
    {id:'huaynaPicchuClimb2',  src:'/photo/peru/huaynaPicchuClimb2.jpg',  alt:'Huayna Picchu'},
    {id:'huaynaPicchuClimb3',  src:'/photo/peru/huaynaPicchuClimb3.jpg',  alt:'Huayna Picchu'},
    {id:'huaynaPicchuClimb4',  src:'/photo/peru/huaynaPicchuClimb4.jpg',  alt:'Huayna Picchu'},
    {id:'huaynaPicchuClimb5',  src:'/photo/peru/huaynaPicchuClimb5.jpg',  alt:'Huayna Picchu'},
    {id:'huaynaPicchuClimb6',  src:'/photo/peru/huaynaPicchuClimb6.jpg',  alt:'Huayna Picchu'},
    {id:'huaynaPicchuClimb7',  src:'/photo/peru/huaynaPicchuClimb7.jpg',  alt:'Huayna Picchu'},
    {id:'huaynaPicchuClimb8',  src:'/photo/peru/huaynaPicchuClimb8.jpg',  alt:'Huayna Picchu'},
    {id:'huaynaPicchuClimb9',  src:'/photo/peru/huaynaPicchuClimb9.jpg',  alt:'Huayna Picchu'},
    {id:'huaynaPicchuClimb10', src:'/photo/peru/huaynaPicchuClimb10.jpg', alt:'Huayna Picchu'},
    {id:'huaynaPicchuClimb11', src:'/photo/peru/huaynaPicchuClimb11.jpg', alt:'Huayna Picchu'},
    {id:'huaynaPicchuClimb12', src:'/photo/peru/huaynaPicchuClimb12.jpg', alt:'Huayna Picchu'},
    {id:'huaynaPicchuClimb13', src:'/photo/peru/huaynaPicchuClimb13.jpg', alt:'Huayna Picchu'},
    {id:'huaynaPicchuClimb14', src:'/photo/peru/huaynaPicchuClimb14.jpg', alt:'Huayna Picchu'},
    {id:'huaynaPicchuClimb15', src:'/photo/peru/huaynaPicchuClimb15.jpg', alt:'Huayna Picchu'},
    {id:'huaynaPicchuClimb16', src:'/photo/peru/huaynaPicchuClimb16.jpg', alt:'Huayna Picchu'},
    {id:'huaynaPicchuClimb17', src:'/photo/peru/huaynaPicchuClimb17.jpg', alt:'Huayna Picchu'},
    {id:'huaynaPicchuBajada1', src:'/photo/peru/huaynaPicchuBajada1.jpg', alt:'Huayna Picchu'},
    {id:'huaynaPicchuBajada2', src:'/photo/peru/huaynaPicchuBajada2.jpg', alt:'Huayna Picchu'},
    {id:'huaynaPicchuBajada3', src:'/photo/peru/huaynaPicchuBajada3.jpg', alt:'Huayna Picchu'},
    {id:'huaynaPicchuBajada4', src:'/photo/peru/huaynaPicchuBajada4.jpg', alt:'Huayna Picchu'},
    {id:'huaynaPicchuBajada5', src:'/photo/peru/huaynaPicchuBajada5.jpg', alt:'Huayna Picchu'},
    {id:'huaynaPicchuBajada6', src:'/photo/peru/huaynaPicchuBajada6.jpg', alt:'Huayna Picchu'},
    {id:'huaynaPicchuBajada7', src:'/photo/peru/huaynaPicchuBajada7.jpg', alt:'Huayna Picchu'},
    {id:'huaynaPicchuBajada8', src:'/photo/peru/huaynaPicchuBajada8.jpg', alt:'Huayna Picchu'},
    {id:'huaynaPicchuBajada9', src:'/photo/peru/huaynaPicchuBajada9.jpg', alt:'Huayna Picchu'},
    {id:'valleSagrado1',       src:'/photo/peru/valleSagrado1.jpg',       alt:'Valle Sagrado'},
    {id:'valleSagrado2',       src:'/photo/peru/valleSagrado2.jpg',       alt:'Valle Sagrado'},
    {id:'valleSagrado3',       src:'/photo/peru/valleSagrado3.jpg',       alt:'Valle Sagrado'},
    {id:'valleSagrado4',       src:'/photo/peru/valleSagrado4.jpg',       alt:'Valle Sagrado'},
    {id:'valleSagrado5',       src:'/photo/peru/valleSagrado5.jpg',       alt:'Valle Sagrado'},
    {id:'valleSagrado6',       src:'/photo/peru/valleSagrado6.jpg',       alt:'Valle Sagrado'},
    {id:'valleSagrado7',       src:'/photo/peru/valleSagrado7.jpg',       alt:'Valle Sagrado'},
    {id:'valleSagrado8',       src:'/photo/peru/valleSagrado8.jpg',       alt:'Valle Sagrado'},
    {id:'valleSagrado9',       src:'/photo/peru/valleSagrado9.jpg',       alt:'Valle Sagrado'},
    {id:'valleSagrado10',      src:'/photo/peru/valleSagrado10.jpg',      alt:'Valle Sagrado'},
    {id:'valleSagrado11',      src:'/photo/peru/valleSagrado11.jpg',      alt:'Valle Sagrado'},
    {id:'valleSagrado12',      src:'/photo/peru/valleSagrado12.jpg',      alt:'Valle Sagrado'},
    {id:'valleSagrado13',      src:'/photo/peru/valleSagrado13.jpg',      alt:'Valle Sagrado'},
    {id:'valleSagrado14',      src:'/photo/peru/valleSagrado14.jpg',      alt:'Valle Sagrado'},
    {id:'valleSagrado15',      src:'/photo/peru/valleSagrado15.jpg',      alt:'Valle Sagrado'},
    {id:'valleSagrado16',      src:'/photo/peru/valleSagrado16.jpg',      alt:'Valle Sagrado'},
    {id:'valleSagrado17',      src:'/photo/peru/valleSagrado17.jpg',      alt:'Valle Sagrado'},
    {id:'valleSagrado18',      src:'/photo/peru/valleSagrado18.jpg',      alt:'Valle Sagrado'},
    {id:'valleSagrado19',      src:'/photo/peru/valleSagrado19.jpg',      alt:'Valle Sagrado'},
    {id:'valleSagrado20',      src:'/photo/peru/valleSagrado20.jpg',      alt:'Valle Sagrado'},
    {id:'valleSagrado21',      src:'/photo/peru/valleSagrado21.jpg',      alt:'Valle Sagrado'},
];

export default peruPhotoArr;