const sanFranciscoPhotoArr = [
    {id:'muirWoodsBW1',  src:'/photo/sanFrancisco/muirWoodsBW1.jpg',  alt:'Muir Woods B&W'},
    {id:'muirWoodsBW2',  src:'/photo/sanFrancisco/muirWoodsBW2.jpg',  alt:'Muir Woods B&W'},
    {id:'muirWoodsBW3',  src:'/photo/sanFrancisco/muirWoodsBW3.jpg',  alt:'Muir Woods B&W'},
    {id:'muirWoodsBW4',  src:'/photo/sanFrancisco/muirWoodsBW4.jpg',  alt:'Muir Woods B&W'},
    {id:'muirWoodsBW5',  src:'/photo/sanFrancisco/muirWoodsBW5.jpg',  alt:'Muir Woods B&W'},
    {id:'muirWoodsBW6',  src:'/photo/sanFrancisco/muirWoodsBW6.jpg',  alt:'Muir Woods B&W'},
    {id:'muirWoodsBW7',  src:'/photo/sanFrancisco/muirWoodsBW7.jpg',  alt:'Muir Woods B&W'},
    {id:'muirWoodsBW8',  src:'/photo/sanFrancisco/muirWoodsBW8.jpg',  alt:'Muir Woods B&W'},
    {id:'muirWoodsBW9',  src:'/photo/sanFrancisco/muirWoodsBW9.jpg',  alt:'Muir Woods B&W'},
    {id:'muirWoodsBW10', src:'/photo/sanFrancisco/muirWoodsBW10.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW11', src:'/photo/sanFrancisco/muirWoodsBW11.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW12', src:'/photo/sanFrancisco/muirWoodsBW12.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW13', src:'/photo/sanFrancisco/muirWoodsBW13.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW14', src:'/photo/sanFrancisco/muirWoodsBW14.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW15', src:'/photo/sanFrancisco/muirWoodsBW15.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW16', src:'/photo/sanFrancisco/muirWoodsBW16.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW17', src:'/photo/sanFrancisco/muirWoodsBW17.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW18', src:'/photo/sanFrancisco/muirWoodsBW18.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW19', src:'/photo/sanFrancisco/muirWoodsBW19.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW20', src:'/photo/sanFrancisco/muirWoodsBW20.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW21', src:'/photo/sanFrancisco/muirWoodsBW21.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW22', src:'/photo/sanFrancisco/muirWoodsBW22.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW23', src:'/photo/sanFrancisco/muirWoodsBW23.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW24', src:'/photo/sanFrancisco/muirWoodsBW24.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW25', src:'/photo/sanFrancisco/muirWoodsBW25.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW26', src:'/photo/sanFrancisco/muirWoodsBW26.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW27', src:'/photo/sanFrancisco/muirWoodsBW27.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW28', src:'/photo/sanFrancisco/muirWoodsBW28.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW29', src:'/photo/sanFrancisco/muirWoodsBW29.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW30', src:'/photo/sanFrancisco/muirWoodsBW30.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW31', src:'/photo/sanFrancisco/muirWoodsBW31.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW32', src:'/photo/sanFrancisco/muirWoodsBW32.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoodsBW33', src:'/photo/sanFrancisco/muirWoodsBW33.jpg', alt:'Muir Woods B&W'},
    {id:'muirWoods2',    src:'/photo/sanFrancisco/muirWoods2.jpg',    alt:'Muir Woods'},
    {id:'muirWoods3',    src:'/photo/sanFrancisco/muirWoods3.jpg',    alt:'Muir Woods'},
    {id:'muirWoods4',    src:'/photo/sanFrancisco/muirWoods4.jpg',    alt:'Muir Woods'},
    {id:'muirWoods5',    src:'/photo/sanFrancisco/muirWoods5.jpg',    alt:'Muir Woods'},
    {id:'muirWoods1',    src:'/photo/sanFrancisco/muirWoods1.jpg',    alt:'Muir Woods'},
    {id:'muirWoods6',    src:'/photo/sanFrancisco/muirWoods6.jpg',    alt:'Muir Woods'},
    {id:'muirWoods7',    src:'/photo/sanFrancisco/muirWoods7.jpg',    alt:'Muir Woods'},
    {id:'muirWoods8',    src:'/photo/sanFrancisco/muirWoods8.jpg',    alt:'Muir Woods'},
    {id:'muirWoods9',    src:'/photo/sanFrancisco/muirWoods9.jpg',    alt:'Muir Woods'},
    {id:'muirWoods10',   src:'/photo/sanFrancisco/muirWoods10.jpg',   alt:'Muir Woods'},
    {id:'muirWoods11',   src:'/photo/sanFrancisco/muirWoods11.jpg',   alt:'Muir Woods'},
    {id:'muirWoods12',   src:'/photo/sanFrancisco/muirWoods12.jpg',   alt:'Muir Woods'},
    {id:'muirWoods13',   src:'/photo/sanFrancisco/muirWoods13.jpg',   alt:'Muir Woods'},
    {id:'muirWoods14',   src:'/photo/sanFrancisco/muirWoods14.jpg',   alt:'Muir Woods'},
    {id:'muirWoods15',   src:'/photo/sanFrancisco/muirWoods15.jpg',   alt:'Muir Woods'},
    {id:'muirWoods16',   src:'/photo/sanFrancisco/muirWoods16.jpg',   alt:'Muir Woods'},
    {id:'muirWoods17',   src:'/photo/sanFrancisco/muirWoods17.jpg',   alt:'Muir Woods'},
    {id:'muirWoods18',   src:'/photo/sanFrancisco/muirWoods18.jpg',   alt:'Muir Woods'},
    {id:'muirWoods19',   src:'/photo/sanFrancisco/muirWoods19.jpg',   alt:'Muir Woods'},
    {id:'muirWoods20',   src:'/photo/sanFrancisco/muirWoods20.jpg',   alt:'Muir Woods'},
    {id:'muirWoods21',   src:'/photo/sanFrancisco/muirWoods21.jpg',   alt:'Muir Woods'},
    {id:'muirWoods22',   src:'/photo/sanFrancisco/muirWoods22.jpg',   alt:'Muir Woods'},
    {id:'muirWoods23',   src:'/photo/sanFrancisco/muirWoods23.jpg',   alt:'Muir Woods'},
    {id:'muirWoods24',   src:'/photo/sanFrancisco/muirWoods24.jpg',   alt:'Muir Woods'},
    {id:'muirWoods25',   src:'/photo/sanFrancisco/muirWoods25.jpg',   alt:'Muir Woods'},
    {id:'muirWoods26',   src:'/photo/sanFrancisco/muirWoods26.jpg',   alt:'Muir Woods'},
    {id:'muirWoods27',   src:'/photo/sanFrancisco/muirWoods27.jpg',   alt:'Muir Woods'},
    {id:'muirWoods28',   src:'/photo/sanFrancisco/muirWoods28.jpg',   alt:'Muir Woods'},
    {id:'muirWoods29',   src:'/photo/sanFrancisco/muirWoods29.jpg',   alt:'Muir Woods'},
    {id:'muirWoods30',   src:'/photo/sanFrancisco/muirWoods30.jpg',   alt:'Muir Woods'},
    {id:'sanFrancisco1', src:'/photo/sanFrancisco/sanFrancisco1.jpg', alt:'San Francisco'},
    {id:'sanFrancisco2', src:'/photo/sanFrancisco/sanFrancisco2.jpg', alt:'San Francisco'},
    {id:'sausalito1',    src:'/photo/sanFrancisco/sausalito1.jpg',    alt:'Sausalito'},
    {id:'sausalito2',    src:'/photo/sanFrancisco/sausalito2.jpg',    alt:'Sausalito'},
    {id:'sausalito3',    src:'/photo/sanFrancisco/sausalito3.jpg',    alt:'Sausalito'},
    {id:'sausalito4',    src:'/photo/sanFrancisco/sausalito4.jpg',    alt:'Sausalito'},
    {id:'sausalito5',    src:'/photo/sanFrancisco/sausalito5.jpg',    alt:'Sausalito'},
    {id:'sausalito6',    src:'/photo/sanFrancisco/sausalito6.jpg',    alt:'Sausalito'},
    {id:'sausalito7',    src:'/photo/sanFrancisco/sausalito7.jpg',    alt:'Sausalito'},
    {id:'sausalito8',    src:'/photo/sanFrancisco/sausalito8.jpg',    alt:'Sausalito'},
    {id:'sausalito9',    src:'/photo/sanFrancisco/sausalito9.jpg',    alt:'Sausalito'},
    {id:'sausalito10',   src:'/photo/sanFrancisco/sausalito10.jpg',   alt:'Sausalito'},
    {id:'sausalito11',   src:'/photo/sanFrancisco/sausalito11.jpg',   alt:'Sausalito'},
    {id:'bcnSf1',        src:'/photo/sanFrancisco/bcnSf1.jpg',        alt:'Barcelona San Francisco double exposure'},
    {id:'bcnSf2',        src:'/photo/sanFrancisco/bcnSf2.jpg',        alt:'Barcelona San Francisco double exposure'},
    {id:'bcnSf3',        src:'/photo/sanFrancisco/bcnSf3.jpg',        alt:'Barcelona San Francisco double exposure'},
    {id:'bcnSf4',        src:'/photo/sanFrancisco/bcnSf4.jpg',        alt:'Barcelona San Francisco double exposure'},
    {id:'bcnSf5',        src:'/photo/sanFrancisco/bcnSf5.jpg',        alt:'Barcelona San Francisco double exposure'},
    {id:'bcnSf6',        src:'/photo/sanFrancisco/bcnSf6.jpg',        alt:'Barcelona San Francisco double exposure'},
    {id:'bcnSf7',        src:'/photo/sanFrancisco/bcnSf7.jpg',        alt:'Barcelona San Francisco double exposure'},
    {id:'bcnSf8',        src:'/photo/sanFrancisco/bcnSf8.jpg',        alt:'Barcelona San Francisco double exposure'},
    {id:'bcnSf9',        src:'/photo/sanFrancisco/bcnSf9.jpg',        alt:'Barcelona San Francisco double exposure'},
    {id:'bcnSf10',       src:'/photo/sanFrancisco/bcnSf10.jpg',       alt:'Barcelona San Francisco double exposure'},
    {id:'bcnSf11',       src:'/photo/sanFrancisco/bcnSf11.jpg',       alt:'Barcelona San Francisco double exposure'},
    {id:'bcnSf12',       src:'/photo/sanFrancisco/bcnSf12.jpg',       alt:'Barcelona San Francisco double exposure'},
    {id:'bcnSf13',       src:'/photo/sanFrancisco/bcnSf13.jpg',       alt:'Barcelona San Francisco double exposure'},
];

export default sanFranciscoPhotoArr;