const tainanPhotoArr = [
    { id: 1, src: '/photo/tainan/tainan1.jpg', alt: 'Tainan' },
    { id: 2, src: '/photo/tainan/tainan2.jpg', alt: 'Tainan' },
    { id: 3, src: '/photo/tainan/tainan3.jpg', alt: 'Tainan' },
    { id: 4, src: '/photo/tainan/tainan4.jpg', alt: 'Tainan' },
    { id: 5, src: '/photo/tainan/tainan5.jpg', alt: 'Tainan' },
    { id: 6, src: '/photo/tainan/tainan6.jpg', alt: 'Tainan' },
    { id: 7, src: '/photo/tainan/tainan7.jpg', alt: 'Tainan' },
    { id: 8, src: '/photo/tainan/tainan8.jpg', alt: 'Tainan' },
    { id: 9, src: '/photo/tainan/tainan9.jpg', alt: 'Tainan' },
    { id: 10, src: '/photo/tainan/tainan10.jpg', alt: 'Tainan' },
    { id: 11, src: '/photo/tainan/tainan11.jpg', alt: 'Tainan' },
    { id: 12, src: '/photo/tainan/tainan12.jpg', alt: 'Tainan' },
    { id: 13, src: '/photo/tainan/tainan13.jpg', alt: 'Tainan' },
    { id: 14, src: '/photo/tainan/tainan14.jpg', alt: 'Tainan' },
    { id: 15, src: '/photo/tainan/tainan15.jpg', alt: 'Tainan' },
    { id: 16, src: '/photo/tainan/tainan16.jpg', alt: 'Tainan' },
    { id: 17, src: '/photo/tainan/tainan17.jpg', alt: 'Tainan' },
    { id: 18, src: '/photo/tainan/tainan18.jpg', alt: 'Tainan' },
    { id: 19, src: '/photo/tainan/tainan19.jpg', alt: 'Tainan' },
    { id: 20, src: '/photo/tainan/tainan20.jpg', alt: 'Tainan' },
    { id: 21, src: '/photo/tainan/tainan21.jpg', alt: 'Tainan' },
    { id: 22, src: '/photo/tainan/tainan22.jpg', alt: 'Tainan' },
    { id: 23, src: '/photo/tainan/tainan23.jpg', alt: 'Tainan' },
    { id: 24, src: '/photo/tainan/tainan24.jpg', alt: 'Tainan' },
    { id: 25, src: '/photo/tainan/tainan25.jpg', alt: 'Tainan' },
    { id: 26, src: '/photo/tainan/tainan26.jpg', alt: 'Tainan' },
    { id: 27, src: '/photo/tainan/tainan27.jpg', alt: 'Tainan' },
    { id: 28, src: '/photo/tainan/tainan28.jpg', alt: 'Tainan' },
    { id: 29, src: '/photo/tainan/tainan29.jpg', alt: 'Tainan' },
    { id: 30, src: '/photo/tainan/tainan30.jpg', alt: 'Tainan' },
    { id: 31, src: '/photo/tainan/tainan31.jpg', alt: 'Tainan' },
    { id: 32, src: '/photo/tainan/tainan32.jpg', alt: 'Tainan' },
    { id: 33, src: '/photo/tainan/tainan33.jpg', alt: 'Tainan' },
    { id: 34, src: '/photo/tainan/tainan34.jpg', alt: 'Tainan' },
    { id: 35, src: '/photo/tainan/tainan35.jpg', alt: 'Tainan' },
    { id: 36, src: '/photo/tainan/tainan36.jpg', alt: 'Tainan' },
    { id: 37, src: '/photo/tainan/tainan37.jpg', alt: 'Tainan' },
    { id: 38, src: '/photo/tainan/tainan38.jpg', alt: 'Tainan' },
    { id: 39, src: '/photo/tainan/tainan39.jpg', alt: 'Tainan' },

];

export default tainanPhotoArr;