const taipeiPhotoArr = [
    { id: 1, src: '/photo/taipei/taipei1.jpg', alt: 'Taipei' },
    { id: 2, src: '/photo/taipei/taipei2.jpg', alt: 'Taipei' },
    { id: 3, src: '/photo/taipei/taipei3.jpg', alt: 'Taipei' },
    { id: 4, src: '/photo/taipei/taipei4.jpg', alt: 'Taipei' },
    { id: 5, src: '/photo/taipei/taipei5.jpg', alt: 'Taipei' },
    { id: 6, src: '/photo/taipei/taipei6.jpg', alt: 'Taipei' },
    { id: 7, src: '/photo/taipei/taipei7.jpg', alt: 'Taipei' },
    { id: 8, src: '/photo/taipei/taipei8.jpg', alt: 'Taipei' },
    { id: 9, src: '/photo/taipei/taipei9.jpg', alt: 'Taipei' },
    { id: 10, src: '/photo/taipei/taipei10.jpg', alt: 'Taipei' },
    { id: 11, src: '/photo/taipei/taipei11.jpg', alt: 'Taipei' },
    { id: 12, src: '/photo/taipei/taipei12.jpg', alt: 'Taipei' },
    { id: 13, src: '/photo/taipei/taipei13.jpg', alt: 'Taipei' },
    { id: 14, src: '/photo/taipei/taipei14.jpg', alt: 'Taipei' },
    { id: 15, src: '/photo/taipei/taipei15.jpg', alt: 'Taipei' },
    { id: 16, src: '/photo/taipei/taipei16.jpg', alt: 'Taipei' },
    { id: 17, src: '/photo/taipei/taipei17.jpg', alt: 'Taipei' },
    { id: 18, src: '/photo/taipei/taipei18.jpg', alt: 'Taipei' },
    { id: 19, src: '/photo/taipei/taipei19.jpg', alt: 'Taipei' },
    { id: 20, src: '/photo/taipei/taipei20.jpg', alt: 'Taipei' },
    { id: 21, src: '/photo/taipei/taipei21.jpg', alt: 'Taipei' },
    { id: 22, src: '/photo/taipei/taipei22.jpg', alt: 'Taipei' },
    { id: 23, src: '/photo/taipei/taipei23.jpg', alt: 'Taipei' },
    { id: 24, src: '/photo/taipei/taipei24.jpg', alt: 'Taipei' },
    { id: 25, src: '/photo/taipei/taipei25.jpg', alt: 'Taipei' },
    { id: 26, src: '/photo/taipei/taipei26.jpg', alt: 'Taipei' },
    { id: 27, src: '/photo/taipei/taipei27.jpg', alt: 'Taipei' },
    { id: 28, src: '/photo/taipei/taipei28.jpg', alt: 'Taipei' },
    { id: 29, src: '/photo/taipei/taipei29.jpg', alt: 'Taipei' },
    { id: 30, src: '/photo/taipei/taipei30.jpg', alt: 'Taipei' },
    { id: 31, src: '/photo/taipei/taipei31.jpg', alt: 'Taipei' },
    { id: 32, src: '/photo/taipei/taipei32.jpg', alt: 'Taipei' },
    { id: 33, src: '/photo/taipei/taipei33.jpg', alt: 'Taipei' },
    { id: 34, src: '/photo/taipei/taipei34.jpg', alt: 'Taipei' },
    { id: 35, src: '/photo/taipei/taipei35.jpg', alt: 'Taipei' },
    { id: 36, src: '/photo/taipei/taipei36.jpg', alt: 'Taipei' },
    { id: 37, src: '/photo/taipei/taipei37.jpg', alt: 'Taipei' },
    { id: 38, src: '/photo/taipei/taipei38.jpg', alt: 'Taipei' },
    { id: 39, src: '/photo/taipei/taipei39.jpg', alt: 'Taipei' },
    { id: 40, src: '/photo/taipei/taipei40.jpg', alt: 'Taipei' },
    { id: 41, src: '/photo/taipei/taipei41.jpg', alt: 'Taipei' },
    { id: 42, src: '/photo/taipei/taipei42.jpg', alt: 'Taipei' },
    { id: 43, src: '/photo/taipei/taipei43.jpg', alt: 'Taipei' },
    { id: 44, src: '/photo/taipei/taipei44.jpg', alt: 'Taipei' },
    { id: 45, src: '/photo/taipei/taipei45.jpg', alt: 'Taipei' },
    { id: 46, src: '/photo/taipei/taipei46.jpg', alt: 'Taipei' },    

];

export default taipeiPhotoArr;