import React from 'react';
import './../pages/Pages.css';
import { NavLink } from "react-router-dom";

const AIAliens = () => {
  return (
    
    <section className="projectpage">
      {/* <NavLink to="/home" className="navbarspace">
        <p>INÉS RODRÍGUEZ HSU</p>
      </NavLink> */}
      <div className="projecttitle">
        AI Aliens
      </div>
      <div className="project-photogrid">
        <video className="project-allphotos" src='/media/blueAlienVid.mp4' alt="Animation of a blue AI Alien" autoPlay loop></video>
        <video className="project-allphotos" src='/media/blueBlobAlienVid.mp4' alt="Animation of a blue AI Alien" autoPlay loop></video>
        <video className="project-allphotos" src='/media/fluidAlienVid.mp4' alt="Animation of a fluid AI Alien" autoPlay loop></video>
        <video className="project-allphotos" src='/media/skyAlienVid.mp4' alt="Animation of a sky AI Alien" autoPlay loop></video>
        <video className="project-allphotos" src='/media/greyAlienVid.mp4' alt="Animation of a grey AI Alien" autoPlay loop></video>
        <video className="project-allphotos" src='/media/greenAlienVid.mp4' alt="Animation of a gree AI Alien" autoPlay loop></video>
        <video className="project-allphotos" src='/media/redAlienVid.mp4' alt="Animation of a red AI Alien" autoPlay loop></video>
        <video className="project-allphotos" src='/media/colorfulAlienVid.mp4' alt="Animation of a colorful AI Alien" autoPlay loop></video>
        <video className="project-allphotos" src='/media/purpleAlienVid.mp4' alt="Animation of a purple AI Alien" autoPlay loop></video>
        <video className="project-allphotos" src='/media/purpleAlienVid2.mp4' alt="Animation of a purple AI Alien" autoPlay loop></video>
      </div>
      <div className="projectdescription">
      I use an artificial intelligence bot ('Midjourney') to obtain 
        images of what an AI thinks life forms would look like and in what type 
        of world they would live in with prompt words like “life form” and color 
        words. This was inspired by a previous project <NavLink to="/year2235">Year2235</NavLink> in 
        which I envision what footage captured of several alien life 
        forms would look like. I attempt to break from the media stereotypes of 
        alien life as well as preconceptions taken from life forms Earth. I wanted 
        artificial intelligence to give me some ideas, which at the same time could 
        be more objective yet are also based on everything that we humans conceive
        life forms to look like in the internet and media.
        <br /><br />
        For each alien life form I use a picture generated by AI, modify it and 
        create a 3D model with it, then and animate it to give it life.
        <br /><br />
      </div>
      <div className="footer"/>  
    </section>
    
  );
}

export default AIAliens;
